#+BEGIN_COMMENT
.. title: #04
.. slug: 04
.. date: 2020-05-02 17:10:43 UTC+02:00
.. tags: 
.. category: 
.. link: 
.. description: 
.. type: text

#+END_COMMENT

* Schule
Seit sieben Wochen unterrichte ich mit meinen Kollegen von Zuhause aus. Nicht nur den Schülern geht der Schulalltag in der Schule ab. Das Unterrichten über die digitalen Medien ist etwas Neues, aber auch besonders anstrengend. Meine Kollegen sitzen wesentlich länger bei der Arbeit. Meine Arbeitsaufträge in Religion ersetzen meine Unterrichtseinheiten, sind daher keine Hausübung. Vor den Osterferien habe ich jede Woche pro Klasse einen Auftrag erteilt. Jetzt gebe ich einen Auftrag für alle Klassen für zwei Wochen. Im Gegensatz zu meinen Kollegen habe ich die gesamte Schule und damit fast 200 Arbeiten zu korrigieren. 

Am 15. Mai findet eine Konferenz statt - mit physischer Anwesenheit in der Schule? Oder über Videokonferenz? Das ist noch nicht klar.  

* Corona

[[https://www.youtube.com/watch?v=Y6W-JIMCfmo][KenFM am Set: Gespräch mit Prof. Dr. Sucharit Bhakdi zu Covid-19]]


