#+BEGIN_COMMENT
.. title: #05
.. slug: 05
.. date: 2020-07-01 10:17:54 UTC+02:00
.. tags: 
.. category: 
.. link: 
.. description: 
.. type: text

#+END_COMMENT

* Corona
Nach langer Zeit melde ich mich wieder. In der Zwischenzeit hat die Corona-Krise die ganze Welt fest im Griff. Zu diesem Thema gäbe es viel zu schreiben. Im Moment ist es wohl zu verfrüht, darüber ein gutes Urteil zu fällen. Da ich als "Normal-Bürger" kaum an gesicherte und objektive Daten herankomme, muss ich mich auf jene Daten verlassen, welche die diversen Medien preisgeben. Ich habe ab einem (eher frühen) Zeitpunkt beschlossen, mir keine neuen Corona-News mehr anzuhören. Ich habe mich selbst beobachtet und erkannt, dass diese News mich nur in Angst und Unsicherheit versetzen. Vielleicht war das ja genau die Absicht hinter diesen News? Wer weiß ...

** Medien
Ich habe mich vor allem auf folgenden Kanälen informiert: KenFM, ServusTV, Addendum, Prof. Dr. Sucharit Bhakdi, Dr. Raphael Bonelli, ... Mit den Daten wird viel Unfug betrieben und oft auch falsch informiert. Gerade der ORF hat sich in letzter Zeit nicht mit Ruhm bekleckert. Am eigenen Leib habe ich erfahren müssen, wie "gehörig und unterwürfig" selbst engagierte Christen die Bundesregierung "verherrlichen" und jede Massnahme ohne Hinterfragen akzeptieren. Wer anderer Meinung ist, wird ausnahmslos ins Verschwörereck gestellt. Wie wohltuend sind da Medien wie ServusTV.


