#+BEGIN_COMMENT
.. title: #06.org
.. slug: 06org
.. date: 2020-09-12 14:57:23 UTC+02:00
.. tags: 
.. category: 
.. link: 
.. description: 
.. type: text

#+END_COMMENT

* Frieden
Wie kann ich in diesen bewegten Zeiten die innere Ruhe bewahren? Das häufige "sich informieren" mit Hilfe der Medien dient kaum dazu. Was sagen mir die Zhalen, die ich z.B. auf www.orf.at finde? Nicht viel, denn hier finde ich hauptsächlich absolute Zahlen. Sie werden kaum in Beziehung untereinander gesetzt. Diese Relationen muss man selbst herstellen. 

Dazu kommt eine äußerst unglückliche Kommunikation: zuerst verhandelt man Monate lang über die Ampel, führt sie mit den dazugehörigen Maßnahmen ein. Und dann? Werden kurzerhand die Maßnahmen von den Ampelfarben entkoppelt und z.B. trotz grüner Farbe (mit Ausnahme von sieben Bezirken) die Maßnahmen der gelben Ampel in ganz Österreich eingeführt. Das bedeutet NMS in den Schulen (außerhalb der Klassenräumen), in allen Geschäften, in der Gastronomie. In den Bars darf man nicht essen noch trinken - eigentlich können alle Bars zusperren. 

Aber: wo steigen die Zahlen? Eigentlich nur in Wien - dort sehr deutlich. Und da man in Wien nicht willens ist, die Stadt auf orange zu stellen - wird das ganze Land faktisch auf gelb gestellt. 

* Frieden
Also: den inneren Frieden bewahrt man sich, indem man ein ziemlich normales Leben führt und sich auf die Suche nach dem Wahren, Guten und Schönen macht - dh nach Gott.




